site_name: KIF
site_description: A knowledge integration framework based on Wikidata.
site_url: https://ibm.github.io/kif/

theme:
    name: 'material'
    features:
      - content.code.annotate
    font:
      text: IBM Plex
      code: IBM Plex Mono
    palette:
      - scheme: 'default'
        media: '(prefers-color-scheme: light)'
        primary: 'custom'
        toggle:
          icon: 'material/lightbulb'
          name: "Switch to dark mode"
      - scheme: 'slate'
        media: '(prefers-color-scheme: dark)'
        primary: 'custom'
        toggle:
          icon: 'material/lightbulb-outline'
          name: 'Switch to light mode'

repo_name: ibm/kif
repo_url: https://github.com/ibm/kif/
# edit_uri: ""

nav:
  - Introduction: 'index.md'
  - Quickstart: 'quickstart.md'
  - Guides:
    - Data Model: 'guides/data_model.md'
    - RDF: 'guides/rdf.md'
  - API Reference:
    - Context: 'api/context.md'
    - Engine:
      - Engine: 'api/engine.md'
      - Search:
        - Search: 'api/search/abc.md'
      - Store:
        - Store: 'api/store/abc.md'
        - Mixer Store: 'api/store/mixer.md'
        - SPARQL Store: 'api/store/sparql.md'
    - Model:
      - KIF Object: 'api/model/kif_object.md'
      - Term:
        - Term: 'api/model/term/term.md'
        - Closed Term: 'api/model/term/closed_term.md'
        - Open Term:
          - Open Term: 'api/model/term/open_term/open_term.md'
          - Template: 'api/model/term/open_term/template.md'
          - Variable: 'api/model/term/open_term/variable.md'
      - Value:
        - Value: 'api/model/value/value.md'
        - Entity:
          - Entity: 'api/model/value/entity/entity.md'
          - Item: 'api/model/value/entity/item.md'
          - Property: 'api/model/value/entity/property.md'
          - Lexeme: 'api/model/value/entity/lexeme.md'
        - Data Value:
          - Data Value: 'api/model/value/data_value/data_value.md'
          - IRI: 'api/model/value/data_value/iri.md'
          - Text: 'api/model/value/data_value/text.md'
          - String: 'api/model/value/data_value/string.md'
          - External Id: 'api/model/value/data_value/external_id.md'
          - Quantity: 'api/model/value/data_value/quantity.md'
          - Time: 'api/model/value/data_value/time.md'
      - Snak:
        - Snak: 'api/model/snak/snak.md'
        - Value Snak: 'api/model/snak/value_snak.md'
        - Some Value Snak: 'api/model/snak/some_value_snak.md'
        - No Value Snak: 'api/model/snak/no_value_snak.md'
      - Statement:
        - Statement: 'api/model/statement/statement.md'
        - Annotated Statement: 'api/model/statement/annotated_statement.md'
      - Statement Annotations:
        - Qualifier Record: 'api/model/statement_annotations/qualifier_record.md'
        - Reference Record: 'api/model/statement_annotations/reference_record.md'
        - Rank: 'api/model/statement_annotations/rank.md'
      - Graph: 'api/model/graph.md'
      - Filter: 'api/model/filter.md'
    - Vocabulary:
      - DBpedia: 'api/vocabulary/db.md'
      - European Data Portal: 'api/vocabulary/eu.md'
      - FactGrid: 'api/vocabulary/fg.md'
      - PubChem: 'api/vocabulary/pc.md'
      - UniProt: 'api/vocabulary/up.md'
      - Wikidata: 'api/vocabulary/wd.md'

exclude_docs: |
  #*
  *~

extra_css:
  - css/custom.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - mkdocstrings:
      enabled: !ENV [MKDOCSTRINGS, true]
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_section_style: list
            group_by_category: true
            show_root_full_path: false
            show_root_heading: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
